language: objective-c
node_js:
  - "6.2"
install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
  - npm install cordova
  - npm install ios-sim
# w/o ios-deploy ios requirements check fails
  - npm install ios-deploy
  - npm install
  - npm link
script:
  - npm run test-travis
